remote_write:
  - url: "http://standalone:14514/v1/prometheus/write?db=greptime_metrics"
    queue_config:
      capacity: 2500
      max_shards: 200
      max_samples_per_send: 500

scrape_configs:
  - job_name: 'greptimedb'
    scrape_interval: 2s
    static_configs:
      - targets: ['flownode0:5001']
        labels:
          node: 'flownode0'
